apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalrserver-dpl
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
  selector:
    matchLabels:
      app: signalrserver
  template:
    metadata:
       labels:
         app: signalrserver
    spec:
      containers:
      - name: signalrserver
        image: "registry.gitlab.com/ricardosantos9521/github/signalrserver:BUILDNUMBER"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        - name: "REDIS_CONFIG"
          value: redis-signalrserver-svc.default.svc.cluster.local
        resources:
          limits:
            memory: "128Mi"
            cpu: "80m"
        readinessProbe:
          httpGet:
             path: /api/readiness/
             port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      imagePullSecrets:
      - name: secretteamrics
---
apiVersion: v1
kind: Service
metadata:
  name: signalrserver-svc
spec:
  selector:
    app: signalrserver
  ports:
  - port: 80
    nodePort: 30200
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signalrserver-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route_socket"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - http:
      paths:
      - path: /signalr/server/(.*)
        backend:
          serviceName: signalrserver-svc
          servicePort: 80