apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-chatserver-dpl
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-chatserver-app
  template:
    metadata:
      labels:
        app: redis-chatserver-app
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "200Mi"
            cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-chatserver-svc
  namespace: chat
spec:
  selector:
    app: redis-chatserver-app
  ports:
  - port: 6379