apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-chattestserver-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-chattestserver
  template:
    metadata:
      labels:
        app: redis-chattestserver
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "200Mi"
            cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-chattestserver-svc
spec:
  selector:
    app: redis-chattestserver
  ports:
  - port: 6379
    nodePort: 6379
  type: NodePort