apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-signalrserver-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-signalrserver
  template:
    metadata:
      labels:
        app: redis-signalrserver
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-signalrserver-svc
spec:
  selector:
    app: redis-signalrserver
  ports:
  - port: 6379
    targetPort: 6379
  externalIPs:
    - 192.168.1.150