apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - name: redis
        image: redis:5.0.3
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis-pod
  type: NodePort
  ports:
  - port: 6379
    nodePort: 31500
  externalIPs:
  - 192.168.1.150
---